app:
  database:
    access-type: jpa
  scheduler:
    interval: 10s
    threads-count: 2
    batch-size: 10
    max-links-per-run: 100
    error-threshold: 5
  valkey:
    enabled: true
    ttl: 1h
    max-size: 1000
    nodes:
      - "localhost:6379"
      - "localhost:6380"
      - "localhost:6381"
    invalidation-topic: "cache-invalidation"
    password: "testpassword"
  github:
    url: "https://api.github.com"
    token: "test-token"
  stackoverflow:
    url: "https://api.stackexchange.com"
    key: "test-key"
    access-token: "test-token"
  kafka:
    bootstrap-servers: localhost:9092
    topic: link_updates
    partitions: 1
    replicas: 1
    min-insync-replicas: "1"
    outbox-check-interval: 10s
    outbox-cleanup-interval: 1m
  bot-client:
    base-url: "http://localhost:8090"
    grpc-channel-name: "bot-channel"


spring:
  main:
    allow-bean-definition-overriding: true

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 1s
  instances:
    scrapper:
      baseConfig: default
    github:
      baseConfig: default
    stackoverflow:
      baseConfig: default

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      minimumRequiredCalls: 5
      failureRateThreshold: 50
      permittedCallsInHalfOpenState: 5
      waitDurationInOpenState: 1s
  instances:
    scrapper:
      baseConfig: default
    github:
      baseConfig: default
    stackoverflow:
      baseConfig: default

app.retry.statuses: 500,502,503,504,429
resilience4j.retry.instances.bot.baseConfig: default
resilience4j.circuitbreaker.instances.bot.baseConfig: default

resilience4j.ratelimiter:
  configs:
    default:
      limitForPeriod: 100
      limitRefreshPeriod: 1s
      timeoutDuration: 0s
    ip-rate-limit:
      limitForPeriod: 50
      limitRefreshPeriod: 1s
      timeoutDuration: 0s
