server:
  port: 8080

spring:
  application:
    name: bot

  main:
    allow-bean-definition-overriding: true

  grpc:
    server:
      port: 9090
    client:
      scrapper-channel:
        address: static://${APP_SCRAPPER_HOST:localhost}:9091
        negotiation-type: plaintext

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9094,localhost:9096}

    admin:
      auto-create: false
      properties:
        retry.backoff.ms: 1000

    consumer:
      group-id: "bot-notification-group"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: backend.academy.linktracker.bot.dto.LinkUpdate

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topic: "link_updates"
    retry:
      max-attempts: 3
  retry:
    statuses: 500,502,503,504,429
    initial-interval: 500ms
    multiplier: 1.0

  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN}
    update-listener-sleep: 1s
    debug: false

  scrapper-client:
    base-url: ${APP_SCRAPPER_CLIENT_BASE_URL:http://localhost:8081}
    grpc-channel-name: scrapper-channel

  grpc:
    scrapper-deadline: 5s

  scrapper-client-type: http

logging:
  structured:
    format:
      console: logstash

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 1s
  instances:
    scrapper:
      baseConfig: default
    github:
      baseConfig: default
    stackoverflow:
      baseConfig: default

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      minimumRequiredCalls: 5
      failureRateThreshold: 50
      permittedCallsInHalfOpenState: 5
      waitDurationInOpenState: 1s
  instances:
    scrapper:
      baseConfig: default
    github:
      baseConfig: default
    stackoverflow:
      baseConfig: default

app.retry.statuses: 500,502,503,504,429

resilience4j.ratelimiter:
  configs:
    default:
      limitForPeriod: 100
      limitRefreshPeriod: 1s
      timeoutDuration: 0s
    ip-rate-limit:
      limitForPeriod: 50
      limitRefreshPeriod: 1s
      timeoutDuration: 0s
