server:
  port: 8080

spring:
  application:
    name: bot
  grpc:
    server:
      port: 9090
    client:
      default-channel:
        address: static://${APP_SCRAPPER_HOST:localhost}:9091
        negotiation-type: plaintext

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false
    scrapper-url: http://localhost:8081
  grpc:
    scrapper-deadline: 5s

logging:
  structured:
    format:
      console: logstash
