
resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 1s
  instances:
    scrapper:
      baseConfig: default
    github:
      baseConfig: default
    stackoverflow:
      baseConfig: default

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      minimumRequiredCalls: 5
      failureRateThreshold: 50
      permittedCallsInHalfOpenState: 5
      waitDurationInOpenState: 1s
  instances:
    scrapper:
      baseConfig: default
    github:
      baseConfig: default
    stackoverflow:
      baseConfig: default

app.retry.statuses: 500,502,503,504,429

resilience4j.ratelimiter:
  configs:
    default:
      limitForPeriod: 100
      limitRefreshPeriod: 1s
      timeoutDuration: 0s
    ip-rate-limit:
      limitForPeriod: 50
      limitRefreshPeriod: 1s
      timeoutDuration: 0s
